class BusesService
  def self.locations
    [
      { id: "212", name: '18 DE JULIO' },
      { id: "185", name: '25 DE AGOSTO' },
      { id: "58", name: '25 DE MAYO' },
      { id: "148", name: 'AEROPUERTO' },
      { id: "27", name: 'AGUAS DULCES' },
      { id: "149", name: 'AIGUA' },
      { id: "47", name: 'ARAMINDA' },
      { id: "88", name: 'ARTIGAS' },
      { id: "96", name: 'ASUNCION' },
      { id: "196", name: 'BARKER' },
      { id: "28", name: 'BARRA DE CHUY' },
      { id: "205", name: 'BARRA DE MALDONADO' },
      { id: "150", name: 'BATLLE Y ORDONEZ' },
      { id: "190", name: 'BELL VILLE' },
      { id: "82", name: 'BELLA UNION' },
      { id: "11", name: 'BELLA UNION-R3' },
      { id: "10", name: 'BUENOS AIRES' },
      { id: "90", name: 'BUENOS AIRES POR COLONIA' },
      { id: "138", name: 'BUENOS AIRES POR TIGRE/CLO' },
      { id: "238", name: 'BUENOS AIRES POR TIGRE/NPA' },
      { id: "151", name: 'CABO POLONIO' },
      { id: "97", name: 'CAMBORIU' },
      { id: "197", name: 'CANADA NIETO' },
      { id: "152", name: 'CANELONES' },
      { id: "162", name: 'CAPILLA DEL SAUCE' },
      { id: "48", name: 'CARDAL' },
      { id: "9", name: 'CARDONA' },
      { id: "22", name: 'CARMELO' },
      { id: "29", name: 'CASTILLOS' },
      { id: "59", name: 'CASUPA' },
      { id: "91", name: 'CEBOLLATI' },
      { id: "147", name: 'CERRO CHATO' },
      { id: "164", name: 'CERRO COLORADO' },
      { id: "23", name: 'CHUY' },
      { id: "202", name: 'CHUY-R.8' },
      { id: "6", name: 'COLONIA' },
      { id: "194", name: 'COLONIA MIGUELETE' },
      { id: "75", name: 'COLONIA VALDENSE' },
      { id: "217", name: 'CONCORDIA' },
      { id: "15", name: 'CORDOBA' },
      { id: "99", name: 'CURITIBA' },
      { id: "5", name: 'DOLORES' },
      { id: "7", name: 'DURAZNO' },
      { id: "153", name: 'ECILDA PAULLIER' },
      { id: "102", name: 'FLORIANOPOLIS' },
      { id: "61", name: 'FLORIDA' },
      { id: "60", name: 'FLORIDA POR CARDAL' },
      { id: "218", name: 'FLORIDA POR PANDO' },
      { id: "166", name: 'FRAILE MUERTO' },
      { id: "167", name: 'FRAY  MARCOS' },
      { id: "2", name: 'FRAY BENTOS' },
      { id: "187", name: 'GREGORIO AZNAREZ' },
      { id: "83", name: 'GUICHON' },
      { id: "172", name: 'ISMAEL CORTINAS' },
      { id: "51", name: 'JAUREGUIBERRY' },
      { id: "173", name: 'JOINVILLE' },
      { id: "154", name: 'JOSE ENRIQUE RODO' },
      { id: "50", name: 'JOSE IGNACIO' },
      { id: "73", name: 'JOSE PEDRO VARELA' },
      { id: "76", name: 'JUAN LACAZE' },
      { id: "210", name: 'KM.329-SARANDI DEL YI' },
      { id: "220", name: 'LA CHARQUEADA' },
      { id: "65", name: 'LA CORONILLA' },
      { id: "134", name: 'LA FALDA' },
      { id: "31", name: 'LA FORTALEZA' },
      { id: "32", name: 'LA PALOMA' },
      { id: "66", name: 'LA PEDRERA' },
      { id: "215", name: 'LAGUNA GARZON' },
      { id: "254", name: 'LAS TOSCAS (CARAGUATA)' },
      { id: "92", name: 'LASCANO' },
      { id: "155", name: 'LIBERTAD' },
      { id: "57", name: 'LOS TITANES' },
      { id: "46", name: 'MALDONADO' },
      { id: "189", name: 'MARCOS JUAREZ' },
      { id: "174", name: 'MARISCALA' },
      { id: "201", name: 'MELO-R.7' },
      { id: "67", name: 'MELO-R.8' },
      { id: "13", name: 'MENDOZA' },
      { id: "3", name: 'MERCEDES' },
      { id: "52", name: 'MIGUES' },
      { id: "37", name: 'MINAS' },
      { id: "25", name: 'MINAS-R.7' },
      { id: "53", name: 'MONTES' },
      { id: "1", name: 'MONTEVIDEO' },
      { id: "78", name: 'NUEVA HELVECIA' },
      { id: "17", name: 'NUEVA PALMIRA' },
      { id: "42", name: 'OMBUES DE LAVALLE-R.12' },
      { id: "181", name: 'PALMITAS' },
      { id: "195", name: 'PALO SOLO' },
      { id: "211", name: 'PALOMA DE DZNO' },
      { id: "156", name: 'PAN DE AZUCAR' },
      { id: "157", name: 'PANDO' },
      { id: "192", name: 'PARANA' },
      { id: "38", name: 'PASO DE LOS TOROS' },
      { id: "4", name: 'PAYSANDU' },
      { id: "64", name: 'PAYSANDU-R.2' },
      { id: "108", name: 'PELOTAS' },
      { id: "221", name: 'PIRARAJA' },
      { id: "43", name: 'PIRIAPOLIS' },
      { id: "158", name: 'PORTEZUELO' },
      { id: "109", name: 'PORTO ALEGRE' },
      { id: "77", name: 'PUNTA COLORADA' },
      { id: "33", name: 'PUNTA DEL DIABLO' },
      { id: "44", name: 'PUNTA DEL ESTE' },
      { id: "256", name: 'PUNTA DEL ESTE R.8 Dir' },
      { id: "255", name: 'PUNTA DEL ESTE x PLIS-R.8' },
      { id: "251", name: 'PUNTA DEL ESTE-R.10' },
      { id: "206", name: 'PUNTA DEL ESTE-R.8' },
      { id: "207", name: 'PUNTA DEL ESTE-R.9' },
      { id: "236", name: 'PUNTA NEGRA' },
      { id: "170", name: 'RADIAL JUAN LACAZE' },
      { id: "169", name: 'RADIAL ROSARIO' },
      { id: "68", name: 'RIO BRANCO' },
      { id: "179", name: 'RIO CUARTO' },
      { id: "16", name: 'RIVERA' },
      { id: "34", name: 'ROCHA' },
      { id: "184", name: 'RODRIGUEZ' },
      { id: "79", name: 'ROSARIO' },
      { id: "114", name: 'ROSARIO (R.A.)' },
      { id: "69", name: 'SALTO' },
      { id: "214", name: 'SAN BAUTISTA' },
      { id: "35", name: 'SAN CARLOS' },
      { id: "193", name: 'SAN FRANCISCO (R.A)' },
      { id: "186", name: 'SAN GABRIEL' },
      { id: "85", name: 'SAN GREGORIO' },
      { id: "62", name: 'SAN JACINTO' },
      { id: "36", name: 'SAN JOSE' },
      { id: "63", name: 'SAN JOSE POR CANELONES' },
      { id: "224", name: 'SAN JOSE-R.45' },
      { id: "56", name: 'SAN LUIS' },
      { id: "115", name: 'SAN PABLO' },
      { id: "163", name: 'SAN RAMON' },
      { id: "54", name: 'SANTA ANA' },
      { id: "182", name: 'SANTA CATALINA' },
      { id: "161", name: 'SANTA CLARA DE OLIMAR' },
      { id: "117", name: 'SANTA FE' },
      { id: "183", name: 'SANTA LUCIA' },
      { id: "55", name: 'SANTA LUCIA DEL ESTE' },
      { id: "86", name: 'SANTA MARIA' },
      { id: "213", name: 'SANTA ROSA' },
      { id: "14", name: 'SANTIAGO DE CHILE' },
      { id: "94", name: 'SARANDI DEL YI' },
      { id: "93", name: 'SARANDI GRANDE' },
      { id: "160", name: 'SOCA' },
      { id: "159", name: 'SOLIS DE MATAOJO' },
      { id: "70", name: 'TACUAREMBO' },
      { id: "26", name: 'TALA' },
      { id: "87", name: 'TARARIRAS' },
      { id: "89", name: 'TRANQUERAS' },
      { id: "39", name: 'TREINTA Y TRES' },
      { id: "71", name: 'TRINIDAD' },
      { id: "165", name: 'TUPAMBAE' },
      { id: "240", name: 'VALIZAS-R.10' },
      { id: "24", name: 'VALIZAS-R.9' },
      { id: "168", name: 'VELAZQUEZ' },
      { id: "178", name: 'VENADO TUERTO' },
      { id: "177", name: 'VERGARA' },
      { id: "253", name: 'VICHADERO' },
      { id: "191", name: 'VILLA MARIA' },
      { id: "180", name: 'VILLA MERCEDES' },
      { id: "72", name: 'YOUNG' },
      { id: "95", name: 'ZAPICAN' },
    ]
  end

  def self.get_location_id(name)
    location = locations.find { |location| location[:name] == name }
    location[:id] if location
  end

  def self.companies 
    [
      { id: 1, name: 'AGENCIA C.'},
      { id: 48, name: 'BELGRANO'},
      { id: 2, name: 'BRUNO'},
      { id: 28, name: 'BUQUEBUS'},
      { id: 43, name: 'CAUVI'},
      { id: 3, name: 'CHADRE'},
      { id: 4, name: 'CHEVIAL'},
      { id: 5, name: 'CITA'},
      { id: 34, name: 'COIT'},
      { id: 79, name: 'COL.EXPRESS'},
      { id: 58, name: 'COPA TURISMO'},
      { id: 6, name: 'COPAY'},
      { id: 7, name: 'COPSA'},
      { id: 8, name: 'CORPORACION'},
      { id: 9, name: 'COT'},
      { id: 11, name: 'COTMI'},
      { id: 12, name: 'CROMIN'},
      { id: 13, name: 'CUT'},
      { id: 14, name: 'CYNSA'},
      { id: 39, name: 'EGA'},
      { id: 59, name: 'EL CONDOR'},
      { id: 15, name: 'EL NORTENO'},
      { id: 16, name: 'EMDAL'},
      { id: 37, name: 'ENCON'},
      { id: 46, name: 'EXP. CHAGO'},
      { id: 17, name: 'EXP.MINUANO'},
      { id: 963, name: 'GABARD'},
      { id: 18, name: 'INTERTUR'},
      { id: 20, name: 'NOSSAR'},
      { id: 21, name: 'NUNEZ'},
      { id: 22, name: 'R.DEL  PLATA'},
      { id: 23, name: 'R.DEL SOL'},
      { id: 24, name: 'SABELIN'},
      { id: 41, name: 'TTL'},
      { id: 25, name: 'TURIL'},
      { id: 26, name: 'TURISMAR'},
    ]
  end

  def self.days
    [
      { ref: "all" , value: 'Todos los días' },
      { ref: "1" , value: 'Lunes' },
      { ref: "2" , value: 'Martes' },
      { ref: "3" , value: 'Miércoles' },
      { ref: "4" , value: 'Jueves' },
      { ref: "5" , value: 'Viernes' },
      { ref: "6" , value: 'Sábado' },
      { ref: "7" , value: 'Domingo' },
      { ref: "lu_vi" , value: 'Lunes a Viernes' },
      { ref: "sa_do" , value: 'Sábados y Domingos' },
    ]
  end

  def self.shifts
    [
      { ref: "all", value: 'Todos los turnos' },
      { ref: "m", value: 'Mañana' },
      { ref: "t", value: 'Tarde' },
      { ref: "n", value: 'Noche' },
    ]
  end
end
